const fs=require('fs'),vm=require('vm'),assert=require('assert'),{JSDOM}=require('jsdom');
(async()=>{
let source=fs.readFileSync('worker.js','utf8');source=source.slice(0,source.indexOf('function tttInit')).replace(/^import .*;$/gm,'').replace(/^const WELCOME_IMAGE.*$/m,'');const c=vm.createContext({console});vm.runInContext(source,c);
const st={board:Array(225).fill(null),bonus:Array(225).fill(''),racks:{1:['H','I','A'],2:['B'],3:['C']},bag:['E','A','I','O','T','S','N','R'],scores:{1:12,2:14,3:0},star:-1,starFound:false,surprises:{112:{type:'robin'}},foundSurprises:{},history:[],passes:0,mode:'classic'};
await c.wordsMove(st,[1,2,3],0,{action:'play',placements:[{i:112,l:'H'},{i:113,l:'I'}]},{prepare:()=>({bind:()=>({first:async()=>({})})})});assert.equal(st.scores[1],17);assert.equal(st.scores[2],24);assert.equal(st.scores[3],10);assert.equal(JSON.stringify(st.history[0].adjustments[0].awards),'[{"player":2,"points":10},{"player":3,"points":10}]');
const html=fs.readFileSync('app.html','utf8'),dom=new JSDOM(html,{url:'https://test',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;w.matchMedia=()=>({matches:true});w.fetch=async()=>({ok:true,json:async()=>({})});
w.eval([...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(x=>x[1]).join('\n')+'\n'+fs.readFileSync('tests/fixtures/words-ui.js','utf8')+`\nS.gstate={players:[1,2],names:{1:{name:'Pe-paw'},2:{name:'MomFudge'}}};const last={p:1,score:6,words:[{word:'HAIL',score:6}],note:'Robin Hood! Others +10 each',adjustments:[{type:'robin',delta:0}]};window.receipt=renderPlayBreakdown({history:[last]});window.voice=mysteryVoiceNote(last);`);
assert(w.receipt.includes('MomFudge +10 points'));assert(!w.receipt.includes('0 points · mystery'));assert(w.voice.includes('MomFudge +10 points'));assert(w.voice.includes('Pe-paw keeps the 6 points'));dom.window.close();console.log('PASS: Robin Hood awards each other player exactly 10; actor keeps word score; existing receipts and voice name the recipient.');
})().catch(e=>{console.error(e);process.exitCode=1});
