/* Picture-led Puzzle Room; existing handlers, data and puzzle engine are preserved. */
function pzPictureLobby(m,d,rooms){
 m.classList.add('pz-picture-lobby');
 m.querySelectorAll('[data-pz-room]').forEach(b=>{const id=+b.dataset.pzRoom,r=rooms.find(r=>+r.id===id),kind=/flower|rose|bloom/i.test(r?.name||'')?'garden':id===1?'home':['cove','garden','home'][Math.abs(id)%3];const src={home:'/ohana-family-home-v2.webp',garden:'/ohana-garden-v1.webp',cove:'/ohana-cove-v1.webp'}[kind];b.innerHTML='<img src="'+src+'?asset=binary2" alt=""><b>'+esc(id===1?(S.sync?.familyName||r?.name):r?.name||'Room')+'</b>';});
 const setup=m.querySelector('.pz-setup'),heading=setup.previousElementSibling;
 const builder=document.createElement('details');builder.className='pz-builder';builder.open=!!PZ.builderOpen;builder.innerHTML='<summary><img src="'+(d.thumbs[PZ.cfg.pic]||d.pictures[PZ.cfg.pic]||d.pictures.home)+'" alt="">New puzzle <span>Choose a picture and make it yours</span></summary>';heading.replaceWith(builder);builder.append(setup);builder.ontoggle=()=>{PZ.builderOpen=builder.open;};
 const album=m.querySelector('.pz-album-grid');if(album){const head=album.previousElementSibling,details=document.createElement('details');details.className='pz-album-section';details.open=true;details.innerHTML='<summary>Finished album <span>'+album.children.length+' pictures</span></summary>';head.replaceWith(details);details.append(album);}
 m.querySelectorAll('.pz-album-pic').forEach(b=>{const id=b.dataset.pzAlbumView;const img=document.createElement('img');img.src=pzAuthUrl('/api/album/'+id+'/image');img.alt='';img.loading='lazy';b.prepend(img);});
 m.querySelectorAll('.pz-album-del').forEach(b=>{const menu=document.createElement('details');menu.className='pz-album-options';menu.innerHTML='<summary>Options</summary>';b.before(menu);menu.append(b);});
 const preview=document.createElement('figure');preview.className='pz-selection-preview';preview.innerHTML='<div><img alt="Selected puzzle picture"><i aria-hidden="true"></i></div><figcaption aria-live="polite"></figcaption>';setup.querySelector('.setup-footer').before(preview);
 const update=()=>{const c=PZ.cfg,src=c.pic==='photo'?c.photo:(d.thumbs[c.pic]||d.pictures[c.pic]);preview.querySelector('img').src=src||'';preview.querySelector('figcaption').textContent=(c.name||PZ_PICS.find(p=>p[0]===c.pic)?.[1]||'Family photo')+' · about '+c.pieces+' pieces · '+(PZ_STYLES.find(p=>p[0]===c.style)?.[1]||'Island mix');preview.style.setProperty('--cuts',Math.max(3,Math.round(Math.sqrt(c.pieces*1.5))));};
 m.querySelectorAll('[data-pz-style]').forEach(b=>{const cv=document.createElement('canvas');cv.width=160;cv.height=100;cv.setAttribute('aria-hidden','true');b.prepend(cv);const x=cv.getContext('2d'),type={classic:0,hibiscus:1,honu:2,shell:3,wave:4,leaf:5,heart:6}[b.dataset.pzStyle]??1;const g=x.createLinearGradient(0,0,140,100);g.addColorStop(0,'#77eee2');g.addColorStop(1,'#00818f');x.fillStyle=g;x.strokeStyle='#ffe2a0';x.lineWidth=3;x.beginPath();x.moveTo(35,30);pzEdge(x,35,30,120,30,0,-1,1,55,type);pzEdge(x,120,30,120,82,1,0,1,45,b.dataset.pzStyle==='mix'?6:type);x.lineTo(35,82);x.closePath();x.fill();x.stroke();});
 m.querySelectorAll('[data-pz-size]').forEach(b=>{const icon=document.createElement('span');icon.className='pz-density';icon.setAttribute('aria-hidden','true');icon.style.setProperty('--grid',Math.round(Math.sqrt(+b.dataset.pzSize)));b.prepend(icon);});
 const photo=m.querySelector('.pz-photo');if(photo&&!PZ.cfg.photo){photo.querySelector('.pz-photo-icon').innerHTML='<img src="/ohana-family-home-v2.webp?asset=binary2" alt="">';}const input=m.querySelector('#pz-photo');if(input)input.setAttribute('aria-label','Choose a family photo for your puzzle');
 m.addEventListener('click',()=>queueMicrotask(update));m.querySelector('#pz-name').addEventListener('input',update);update();
}
